name: Landing Page

on:
  push:
  workflow_dispatch:

jobs:
  move:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        
      - name: Set up Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install dependencies
        run: |
          set -e
          npm install
      
      - name: Publish to Wikipedia
        run: |
          set -e
          echo "Hier muss dann das Skript aufgerufen werden, das alles in die Wikipedia bringt."
          
